### ISSUE TITLE
Bootloader fails

### ISSUE THREAD

**Issue by leopardcaun** [ParrotSec/parrot-installer#1]
![screenshot at 2018-04-22 10-58-27](https://user-images.githubusercontent.com/38638107/39102495-54b638d8-4659-11e8-9895-467aec0b0ac7.png)
#### Submission type

  - [ ] Bug report
  - [ ] Feature Request

#### Info regarding which version of Calamares is used, which Distribution

> …

#### Provide information on how the disks are set up, in detail, with full logs of commands issued 

> …

#### What do you expect to have happen when Calamares installs?

> …

#### Describe the issue you encountered

> …

#### Steps to reproduce the problem

> …

#### Include the installation.log:

> …

**Comment by PalinuroSec** [comment]
hello, that installer is still experimental, try to use the debian-installer from the boot menu instead
